### ISSUE TITLE
BoxSync.download fails with "No match found on URL: http://sites.box.com/sync4"

### ISSUE THREAD

**Issue by gregneagle** [autopkg/hansen-m-recipes#103]
http://sites.box.com/sync4 seems to redirect to a login page.

Setting URL to https://community.box.com/t5/Using-Box-Sync/Installing-Box-Sync/ta-p/85 fixes the recipe for now, though I have my doubts about this being a stable URL.  (One can just insert this URL in a recipe override.)

https://www.box.com/resources/downloads has no mentions of Box Sync, so I'm wondering if this is now or soon to be a deprecated product.

**Comment by rustymyers** [comment]
Agreed. I suspect they're deprecating this for Box Drive, once there is an ability to cache local files. We'll probably remove this download when it disappears, but we're still using it for now.

**Comment by rustymyers** [comment]
Also, recipe is fixed.
