### ISSUE TITLE
Prey Download Error

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/hansen-m-recipes#107]
Just started getting these errors on the Prey.munki recipe which references your download recipe. 

`Processor: URLTextSearcher: Error: No match found on URL: https://preyproject.com/download`

Im not great at REGEX I noticed that the format of the download link may have changed slightly. 

The current structure is

https://downloads.preyproject.com/prey-client-releases/node-client/1.7.5/prey-mac-1.7.5-x64.pkg

<string>(?P&lt;url&gt;https:\/\/downloads.preyproject.com\/prey-client-releases\/node-client\/(?P&lt;version&gt;[0-9.]+)\/prey-mac-[0-9.]+-x64\.pkg)</string>

Looks correct but its failing.

**Comment by rustymyers** [comment]
This should be fixed in the latest commit 2f42f2b8b96120d8c63175c5d21bed5d30ab6115

**Comment by jonbrown21** [comment]
Yep works great thanks!
