### ISSUE TITLE
BoxEdit.download.recipe URL changed

### ISSUE THREAD

**Issue by dcoobs** [autopkg/hansen-m-recipes#109]
BoxEdit.download.recipe fails because it looks like Box changed the download URL.

Old URL: https://e3.boxcdn.net/box-installers/boxedit/mac/currentrelease/BoxEditInstaller.dmg
New URL: https://e3.boxcdn.net/box-installers/boxedit/mac/currentrelease/BoxToolsInstaller.dmg

**Comment by rustymyers** [comment]
This should be fixed in the latest commit
