### ISSUE TITLE
Stellarium Recipe Error - Stellarium Has Moved To GitHub

### ISSUE THREAD

**Issue by dcoobs** [autopkg/hansen-m-recipes#110]
Looks like Stellarium has moved from SourceForge to [GitHub](https://github.com/Stellarium/stellarium):
<img src="https://user-images.githubusercontent.com/12276948/44737916-e35c9500-aab8-11e8-943f-0c4dcbb6bf8e.JPG" width="500" height="300">

Now we're seeing errors in the recipe:
`The following recipes failed:

    Stellarium.munki.recipe

        Error in local.munki.Stellarium: Processor: URLTextSearcher: Error: No match found on URL: https://sourceforge.net/projects/stellarium/rss?path=/Stellarium-MacOSX
`

**Comment by rustymyers** [comment]
@dcoobs This has been fixed in the latest commit. Updated to use web page to grab download URL from GitHub releases.
