### ISSUE TITLE
RStudio SSL issue

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/hansen-m-recipes#12]
I get this error related to SSL. (autopkg 0.5.0)

    The following recipes failed:
    RStudio.munki
        Error in local.munki.RStudio: Processor: URLDownloader: Error: Couldn't download https://download1.rstudio.org/RStudio-0.99.467.dmg: <urlopen error [Errno 1] _ssl.c:507: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

**Comment by hansen-m** [comment]
If you do a repo-update it should be fixed now.
