### ISSUE TITLE
NotepadPlusPlus.download Issue

### ISSUE THREAD

**Issue by SirBrent1980** [autopkg/hansen-m-recipes#125]
Looks like they added an additional link on the download page for NotepadPlusPlus that confuses the URLTextSearcher. I switched to using the following already in the recipe which seems to have fixed the download issue:
        
        
        <dict>
            <key>Processor</key>
            <string>URLTextSearcher</string>
            <key>Arguments</key>
            <dict>
                <key>url</key>
                <string>https://notepad-plus-plus.org/update/getDownloadUrl.php</string>
                <key>re_pattern</key>
                <string><![CDATA[<Version>(?P<version>[0-9.]+)</Version>]]></string>
            </dict>
        </dict>
        <dict>
            <key>Processor</key>
            <string>URLTextSearcher</string>
            <key>Arguments</key>
            <dict>
                <key>url</key>
                <string>https://notepad-plus-plus.org/update/getDownloadUrl.php</string>
                <key>re_pattern</key>
                <string><![CDATA[<Location>(?P<url>http.*)<\/Location>]]></string>
            </dict>
        </dict>

**Comment by rustymyers** [comment]
Closed with #126 Thanks!
