### ISSUE TITLE
Add options for Unity3DComponetsURLProvider.py

### ISSUE THREAD

**Issue by apizz** [autopkg/hansen-m-recipes#127]
I was playing around with this processor and the Unity download recipe today in order to get the Unity components downloaded as part of autopkg, but my Python skills need work ...  As it stands, there are a couple of issues I'm experiencing with the `Unity3DComponetsURLProvider` processor:

1. Can't provide anything other than `Unity` for the component to be downloaded.  I'd really like to be able to specify this in the download recipe input, rather than have `Unity` be hardcoded.
2. If it's undesirable (or too much trouble) to update `Unity3DComponetsURLProvider` for this, then it'd be great to add the ability to add `revision` as an output variable.  Looking at the code, it appears that `revision` is used, however this is not setup to be part of the output variables, but this is crucially needed in order to download.

If you go to https://unity3d.com/unity/whats-new/latest, this will redirect you to the latest available release version info page, which includes the direct URLs to the Unity Editor, as well as the various component installers.

However, the `Unity3DComponetsURLProvider` crucially collects the revision number, which is needed in the download URL.  Below is what I've come up with for the `Facebook Games Support` installer if a `revision` output variable were added.

```
<dict>
    <key>Processor</key>
    <string>URLTextSearcher</string>
    <key>Arguments</key>
    <dict>
        <key>url</key>
        <string>https://unity3d.com/unity/whats-new/latest</string>
        <key>re_pattern</key>
        <string>(?P&lt;url&gt;https:\/\/download\.unity3d\.com\/download_unity\/%revision%\/MacEditorTargetInstaller\/UnitySetup-Facebook-Games-Support-for-Editor-(?P&lt;full_version&gt;[\w.]+)\.pkg)</string>
    </dict>
</dict>
```

Ideally, the `re_pattern` would be an input variable so that this one recipe could be used for different component packages, but if `%revision% is to be used in the variable as it is above, I don't think this is possible ...

The URL scheme for each component package is as follows:

`https://download.unity3d.com/download_unity/<revision>/MacEditor[Installer|TargetInstaller]/[Unity|UnitySetup]-<Name of component>-<CFBundleVersion>.pkg`

And while not huge, the processor itself is misspelled slightly.

**Comment by rustymyers** [comment]
Any pull requests are welcome for these issues. I can look at them in the future, but currently not able to spend time on this processor at the moment. Thanks

**Comment by apizz** [comment]
Closing, as this was ultimately determined with the help of @joshua-d-miller and others in the autopkg channel.  Component recipes can be found: https://github.com/autopkg/apizz-recipes/tree/master/Unity
