### ISSUE TITLE
Unity3DComponentsURLProvider failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/hansen-m-recipes#129]
We started seeing the following error a few days ago; I'm wondering if the 'terms of service' checkbox at https://store.unity.com/download is the problem? Manually loading https://store.unity.com/download/thank-you?thank-you=personal&os=osx&nid=1389 does result in a download.

Error in local.munki.Unity3D: Processor: Unity3DComponetsURLProvider: Error: No match found on URL: https://store.unity.com/download/thank-you?thank-you=personal&os=osx&nid=1389

Thanks!

**Comment by Daz-wallace** [comment]
Pull requested submitted #130
