### ISSUE TITLE
Kindle download recipe not parsing URL

### ISSUE THREAD

**Issue by aysiu** [autopkg/hansen-m-recipes#13]
I suspect it has to do with the 301 permanent redirect. The recipe now gives this error:

Processing Kindle.download...

URLTextSearcher

No match found on URL: http://www.amazon.com/gp/kindle/mac/download

Failed.

Receipt written to /Users/admin/Library/AutoPkg/Cache/com.github.hansen-m.download.Kindle/receipts/Kindle-receipt-20150729-095146.plist

The following recipes failed:

    Kindle.download

        Error in com.github.hansen-m.download.Kindle: Processor: URLTextSearcher: Error: No match found on URL: http://www.amazon.com/gp/kindle/mac/download

Nothing downloaded, packaged or imported.

**Comment by hansen-m** [comment]
Not exactly sure how to fix this but I'm open to suggestions. As a workaround I just updated the recipe to use a direct download for the disk image, not sure if the link is persistent between version updates.

**Comment by aysiu** [comment]
Yeah, I'm not sure either. My understanding is that AutoPkg can follow http redirects, but I don't know if it does 301 permanent redirects specified by the server. Thanks for updating!

**Comment by jpenney** [comment]
It looks like the URL to check should now be `http://www.amazon.com/kindlemacdownload/ref=klp_mac`.  Interestingly, that request results in a 404/Not Found, but the body of the response says it's a 301/Moved-Permanently, and contains the current link:

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html><head>
    <title>301 Moved Permanently</title> 
    </head><body>
    <h1>Moved Permanently</h1>
    <p>The document has moved <a href="https://s3.amazonaws.com/kindleformac/43056/KindleForMac-43056.dmg">here</a>.</p>
    </body></html>

Is it possible to parse the link from the content and ignore the 404 status?

**Comment by hansen-m** [comment]
Thanks, in my testing it seems like it is able to follow the 301 redirect without having the scrape the page. Not sure if this works in older versions of autopkg so I've bumped the MinimumVersion requirement just in case. 

https://github.com/autopkg/hansen-m-recipes/commit/911ae39375db91efd5b6313f871dad00adde84e7

**Comment by hansen-m** [comment]
Never mind, that seems to download the old version (1.12.0)... ideas?

**Comment by hansen-m** [comment]
Strike that, it does work but only with the latest (CURL based) version of autopkg.
