### ISSUE TITLE
PolycomRPDesktop.download.recipe

### ISSUE THREAD

**Issue by macmule** [autopkg/hansen-m-recipes#134]
Looks like the download is now behind a EULA, so the recipe fails

**Comment by rustymyers** [comment]
@macmule try the latest commit from today.

**Comment by macmule** [comment]
Thanks @rustymyers that did work, but the cert has expired.

I'm going to leave this as a manual pkg for us for now.

**Comment by rustymyers** [comment]
Sorry, I'm missing it. Which cert has expired that causes it to fail for you?

**Comment by macmule** [comment]
Actually, current is fine.

Except that the pre-install trips over TCC!

This is failing to install due the PKG tripping over TCC, which is a protection introduced with Mojave. I don't know what we can suggest here currently. The PKG's preinstall script is a Shell script which calls either an AppleScript or a 357 line Python script.
