### ISSUE TITLE
Oracle Java JDK download paths have changed

### ISSUE THREAD

**Issue by cache22nz** [autopkg/hansen-m-recipes#136]
Oracle seem to have changed the /otn-pub/ component of the JDK download paths to /otn/. Checked for JDK8 and JDK11. Perhaps change that part of the url search string to /otn.*/, to be more resilient?

**Comment by rustymyers** [comment]
Hello,
Unfortunately, we're unable to support these download recipes with the recent changes to Oracle's site, which requires a log in to download the package. We suggest downloading the package manually and running it through other recipes with the -k pathname=~/path/to.pkg

Rusty
