### ISSUE TITLE
Rhinoceros

### ISSUE THREAD

**Issue by macmule** [autopkg/hansen-m-recipes#139]
https://discourse.mcneel.com/t/rhino-6-for-mac-now-available/86835

Cannot get a valid download URL & cannot find the sparkle feed currently

**Comment by flammable** [comment]
Here's the download page:

https://www.rhino3d.com/download/rhino-for-mac/6/latest

Current download URL is:

http://files.mcneel.com/rhino/6/mac/releases/rhino_6.16.19205.01052.dmg

The "Download Now" button is visible once entering an email address.

**Comment by Daz-wallace** [comment]
Hmmm, I can't seem to find a way to grab that link via AutoPKG :/

**Comment by rustymyers** [comment]
I've been unable to determine how to automate the submission of that email form for getting the download link. I tried a few curl POST requests with different data fields, but I didn't get it working. If anyone figures out how to get that page submitted, I'll write a custom processor for it.

**Comment by Daz-wallace** [comment]
I'm also stuck on this one.
Unless there's a better idea, we might need to abandon it :/

**Comment by flammable** [comment]
I reached out to the developer - hoping to hear something this week.

**Comment by flammable** [comment]
I heard back from the developer. Try this Sparkle feed:

`https://files.mcneel.com/rhino/6/mac/updates/commercialUpdates.xml`

**Comment by rustymyers** [comment]
Thanks @flammable! I've updated the recipe with the new xml and it seems to be fixed!
