### ISSUE TITLE
VueScan recipe no longer appears to be pulling latest version since v9.7.x released

### ISSUE THREAD

**Issue by fseesink** [autopkg/hansen-m-recipes#148]
Until recently, the VueScan recipe worked great.  But with the release of VueScan 9.7.x, it seems the recipe is stuck on the last of the 9.6.x updates (9.6.47).  The website shows the current version to be 9.7.0.3 (8 Oct 2019).

**Comment by rustymyers** [comment]
Try the latest commit with AutoPkg 1.2. That's working for me now.

**Comment by fseesink** [comment]
Yep, that seemed to resolve it.
