### ISSUE TITLE
Catalina wine with MSIVersionProvider

### ISSUE THREAD

**Issue by rustymyers** [autopkg/hansen-m-recipes#150]
MSIVersionProvider utilizes wine to run lessmsi.exe. As of macOS Catalina, wine no longer functions due to the removal of 32bit kernel support or libraries. The following download recipes utilize the MSIVersionProvider:

```
Adobe/AdobeShockwavePlayer-Win.download.recipe
Apple/QuickTime-Win.download.recipe
Apple/iTunes-Win.download.recipe
Box/BoxEdit-Win.download.recipe
SharedProcessors/README.md
Skype/Skype-Win.download.recipe
ThomsonReuters/EndNote-Win.download.recipe
UnixUtils/7zip-Win.download.recipe
UnixUtils/7zip-Win64.download.recipe
```

The Zoom-Win.download has been converted to using URLTextSearcher to find the version on the web site. This might not be possible or desirable, but it works for now. Also, the regex is pretty junky, it could use some help...

    Zoom/Zoom-Win.download.recipe

Other options may be to use a different tool. msitools (https://wiki.gnome.org/msitools) installs on Catalina with:

    brew install msitools

Then the following command can find the version:

    msiinfo export "/Users/sysman/Library/AutoPkg/Cache/local.bigfix.Zoom-Win/downloads/Zoom Video Conferencing.msi" File | awk '/Zoom.exe/ {print $5}'

The issue with this is there is no clear way of getting the version. At least, not clear to me. 

Another option might be to use docker with wine: https://hub.docker.com/r/scottyhardy/docker-wine/
That may provide the best overall solution to utilize lessmsi in the future.

Finally, adding windows support to AutoPkg would be another solution. Then these tools could be run natively.

**Comment by jgstew** [comment]
"The issue with this is there is no clear way of getting the version. At least, not clear to me."

Can you provide example output?

**Comment by jgstew** [comment]
I ran this: `brew install msitools` and now homebrew is updating, and wow my CPU is really going wild.

**Comment by jgstew** [comment]
This will get what you need:

`msiinfo export ZoomInstallerFull.msi Property | grep ProductVersion`

**Comment by jgstew** [comment]
Also, good job finding https://wiki.gnome.org/msitools ... it does exactly what is needed.

**Comment by rustymyers** [comment]
Thanks @jgstew! This looks really promising. I like to use awk for a result like that so I can pull just the second output, such as:

    msiinfo export ZoomInstallerFull.msi Property | awk '/ProductVersion/ {print $2}'

My plan is to update the MSIVersionProvider.py with this new tool. Hopefully I can stage a copy, otherwise I'll just have to have it as a prerequisite. Appreciate the help!!

**Comment by jgstew** [comment]
I've used AWK many times, but I don't remember how it works until I poke at it.

**Comment by jgstew** [comment]
Could make an `msitools` autopkg install recipe.

**Comment by rustymyers** [comment]
Done! msi_path input variable made as backup for standard path to misinformed on macOS
