### ISSUE TITLE
Pencil2D Duplicate Recipe

### ISSUE THREAD

**Issue by apizz** [autopkg/hansen-m-recipes#154]
Hi, there.  Per https://macadmins.slack.com/archives/C056155B4/p1580839875339200, wanted to address our duplicate Pencil2D download recipes.

Mine I didn't create until much more recently, however this pulls from Github using the `GitHubReleasesInfoProvider` where we can get things like version and other data that we can't get from Bitbucket.  Didn't know if you felt strongly about hanging on to your existing recipe, but my preference would be to keep mine given the additional data we get from that Github processor.

That being said, the original reason for creating the recipe no longer exists, as the teacher that wanted the software opted not to ultimately use it.  So if you'd prefer to maintain ownership of the recipe and just replace your recipe with mine, I'll just deprecate mine, no problem.

**Comment by rustymyers** [comment]
The latest commit has a depreciation warning in the recipe and suggests com.github.apizz.download.Pencil2D as a replacement. I'll leave the recipe in place for a little time and then remove it. Thanks
