### ISSUE TITLE
SharedProcessors not working with AutoPkg 2 (possibly not Python 3 compatible)

### ISSUE THREAD

**Issue by andredb90** [autopkg/hansen-m-recipes#157]
Since AutoPkg 2 migrated to Python 3 I'm not able to use the certain windows recipes anymore. Trying to run FirefoxESR64-Win.download and GoogleChrome-Win64.download throws the following errors. 

Processor: com.github.hansen-m.SharedProcessors/GoogleChromeWinVersioner: Error: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte

Processor: com.github.hansen-m.SharedProcessors/BESRelevanceProvider: Error: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

Is it possible to make the processors compatible with the latest version of AutoPkg?

**Comment by rustymyers** [comment]
Working on this. Has to have some of the besapi code updated for other parts of the tools. It going to take a bit to get everything transitioned over to python3. Until then, you can try the python3 branch or use AutoPkg 1.4. Thanks!

**Comment by rustymyers** [comment]
@andredb90 This should be resolved with the latest releases of the besapi and AutoPkgBESEngine. Please update to the latest versions and try again. Thanks
