### ISSUE TITLE
MSIInfoVersionProvider

### ISSUE THREAD

**Issue by SirBrent1980** [autopkg/hansen-m-recipes#161]
When I run my download recipes for MSI files it either stops abruptly when it tries to get the version information and does not create a receipt or other recipes give me an error as follows:

Processor: com.github.hansen-m.ShareProcessors/MSIInfoVersionProvider: Error: a bytes like object is required, not 'str'

I recently upgraded to AutoPkg 2.0.2. I'm still running High Sierra. I recently did a repo-update all as well and since then I've been getting these issues.  What am I missing?

**Comment by rustymyers** [comment]
@SirBrent1980 looks like some bad encoding/decoding that caused the output from the msiinfo command to fail to split it. Please try the latest commits (autopkg repo-update hansen-m-recipes). If it fails, send me the recipe you tried and any output. Thanks

**Comment by SirBrent1980** [comment]
@rustymyers your changes have resolved my issues! Thanks for your quick response. I appreciate everything you do. Thanks again!
