### ISSUE TITLE
Anaconda3 URL changes

### ISSUE THREAD

**Issue by flammable** [autopkg/hansen-m-recipes#164]
The URL for Anaconda3 has changed to this:

`https://www.anaconda.com/products/individual#macos`

That's easy enough to change. However, it looks like the regex needs to be updated, too. The current package URL is this:

`https://repo.anaconda.com/archive/Anaconda3-2020.02-MacOSX-x86_64.pkg`

However, I'm getting stuck on updating [this](https://github.com/autopkg/hansen-m-recipes/blob/master/Continuum/Anaconda.download.recipe#L22) to match the new version string. Any ideas?

**Comment by rustymyers** [comment]
Looks like the first re_pattern needs to have the "version" word removed, as that text was removed from the web page.

**Comment by rustymyers** [comment]
The latest commit should resolve this issue.

**Comment by flammable** [comment]
Thanks!
