### ISSUE TITLE
[Inkscape] URLTextSearcher: Error: No match found on URL

### ISSUE THREAD

**Issue by oliverweinm** [autopkg/hansen-m-recipes#175]
The Inkscape.download recipe does currently not work due to the error:

**_Error in com.github.hansen-m.download.Inkscape: Processor: URLTextSearcher: Error: No match found on URL: https://inkscape.org/en/release/_**

This most likely stems from a recent redesign of the **https://inkscape.org/release/** and the fact that the old link **https://inkscape.org/en/release/** doesn't exist anymore causing the previous regex search patterns to fail. 
On top of that, inkscape.org/release/ seems to only show the download links to the most recent (stable) version which sometimes is not available for macOS yet (as is the case right now).

I do not have a permanent solution yet, but I will get back if I have one. 
Inkscape does provide a link which automatically is only a couple days behind the master branch (**http://alpha.inkscape.org/prereleases/Inkscape-latest.dmg**) but the downsides to that may be instability and performance issues.

I will make a pull request for a temporary fix which comments out the URLTextSearcher processors hardcodes the link for version 1.0.0, since that hasn't been downloadable on our AutoPkgr build host yet.

**Comment by oliverweinm** [comment]
I've made the pull request now :) : #176

**Comment by rustymyers** [comment]
Pull #176 resolves this issue. Thanks!!
