### ISSUE TITLE
Typo in DymoLabel.download.recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/hansen-m-recipes#189]
Getting the following error from our CI workflow, even though we don't use the DYMO recipe:

WARNING: plist error for /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Dymo/DymoLabel.download.recipe: unexpected element at line 51.

Looks like the problem is at line 23, which shouldn't be commented out.

**Comment by rustymyers** [comment]
Thanks for letting us know, this should be fixed now.
