### ISSUE TITLE
Change to RStudio.download SEARCH_URL

### ISSUE THREAD

**Issue by eshirk** [autopkg/hansen-m-recipes#199]
Looks like the download URL for RStudio has changed from

https://www.rstudio.com/products/rstudio/download/

to

https://www.rstudio.com/products/rstudio/download/#download

**Comment by rustymyers** [comment]
RStudio has added a + between the version and build now. Looks like the + is in all the versions in the app.
Updated regex to grab the +, but comes in as %2B:

version': '2021.09.0%2B351'

App Info.plist:
	<key>CFBundleLongVersionString</key>
	<string>2021.09.0+351</string>
	<key>CFBundleShortVersionString</key>
	<string>2021.09.0+351</string>
	<key>CFBundleVersion</key>
	<string>2021.09.0+351</string>

Updated download, but I'd suggest checking children recipes.
