### ISSUE TITLE
Anaconda3.download?

### ISSUE THREAD

**Issue by macmule** [autopkg/hansen-m-recipes#206]
The Anaconda recipe has a deprecation warning which says:

`Anaconda is moving to Python3 as default install. See Anaconda3.download`

What does that mean? I cannot find Anaconda3.download?

**Comment by rustymyers** [comment]
Anaconda3.download has been created.

**Comment by macmule** [comment]
Thanks!

**Comment by MLBZ521** [comment]
Sorry to dig this up, but had a question.  Was there a need for this? The original "Anaconda" recipe allowed for an override to specify the Python3 version.  Or am I missing something?

Thanks!

**Comment by rustymyers** [comment]
@MLBZ521 I think you're right. I put it back in place.
