### ISSUE TITLE
Path to msiinfo differs on Apple Silicon

### ISSUE THREAD

**Issue by patgmac** [autopkg/hansen-m-recipes#208]
https://github.com/autopkg/hansen-m-recipes/blob/0c0dca0074ba59352d400bf3da48c0a4ca3bfdbd/SharedProcessors/MSIInfoVersionProvider.py#L42

On Apple Silicon, the path to msiinfo needs to be: 
`MSIINFO = os.path.abspath("/opt/homebrew/bin/msiinfo")`

**Comment by jgstew** [comment]
Ideally the path to `msiinfo` should be an input variable with a default value that can be overridden.

I have a shared processor called `FileGetExecutable` that you provide an array of paths and it will return the first item it finds that is a real file that is marked executable. I use this to allow many of the processors within this repo to work on Windows and Linux in addition to MacOS by providing many alternative paths including the default ones.

See example usage here: https://github.com/jgstew/jgstew-recipes/blob/main/Test-Recipes/FileGetExecutable.test.recipe.yaml

**Comment by rustymyers** [comment]
Latest commit includes input variable for msiinfo path. Please test and report!
