### ISSUE TITLE
Zoom updates have been separated for m1 and intel

### ISSUE THREAD

**Issue by tsinghzf** [autopkg/hansen-m-recipes#210]
https://zoom.us/download

Zoom Client for Meetings has been set up by the vendor to be separate for lintels and m1s.

Can you please update recipes to accommodate for this?

opened here as well https://github.com/autopkg/jss-recipes/issues/263

**Comment by homebysix** [comment]
Have you tried creating a separate override with `DOWNLOAD_URL` set to `https://zoom.us/client/latest/Zoom.pkg?archType=arm64`? That worked for me (although you may need to force import until [this](https://github.com/autopkg/autopkg/pull/749) capability is merged).

**Comment by homebysix** [comment]
@tsinghzf - Just revisiting and rethinking this, and I wanted to point out that the Zoom "IT Installer" used by the download recipe does in fact deploy a Universal version of Zoom. Is there a reason you're choosing not to use the IT Installer and deploying the consumer installer instead?

**Comment by tsinghzf** [comment]
@homebysix Hi, thanks for confirming that. i noticed that as well but wasn't sure initially. We are using the IT installer.

Thank you ticket can be closed
