### ISSUE TITLE
PyCharm.download.recipe CodeSignature wrong

### ISSUE THREAD

**Issue by mikeknight85** [autopkg/hansen-m-recipes#211]
The CodeSignature changed to: 

`identifier "com.jetbrains.pycharm.ce" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "2ZEFAR8TH3"`

**Comment by rustymyers** [comment]
Please try with latest commits.
