### ISSUE TITLE
WinInstallerExtractor Error

### ISSUE THREAD

**Issue by SirBrent1980** [autopkg/hansen-m-recipes#213]
Looks like this processor was updated recently. Since that time I've been getting an error with recipes using this processor. In the meantime, I've restored an older copy of this processor which works.

"Processor: com.github.hansen-m.SharedProcessors/WinInstallerExtractor: Error: name 'subprocess' is not defined"

**Comment by SirBrent1980** [comment]
@rustymyers All good now! Thanks so much!

**Comment by rustymyers** [comment]
Thanks!
Resolved with bdc0e5d71007953d5288d1bad25ebc281cbf34c7
