### ISSUE TITLE
AstroImageJ.download.recipe

### ISSUE THREAD

**Issue by clawson1** [autopkg/hansen-m-recipes#246]
Prompting to install newer version after install. Download recipe does not seem to be grabbing the latest version.

**Comment by rustymyers** [comment]
AstroImageJ stopped publishing updates to their main page. The software contacts the following URL for the list of updates:
curl -L http://www.astro.louisville.edu/software/astroimagej/updates/updatesjava17/versions.txt
The updates are stored at the same location and can be downloaded with the filename: "ij%version%.jar"
For example:
curl -O -L http://www.astro.louisville.edu/software/astroimagej/updates/updatesjava17/ij5.2.1.jar
