### ISSUE TITLE
Aquamacs.download.recipe returning 404

### ISSUE THREAD

**Issue by jakerundall** [autopkg/hansen-m-recipes#27]
Hi - I've just run the Aquamacs.download.recipe and gotten the following error:
Error in com.github.hansen-m.download.aquamacs: Processor: URLDownloader: Error: Couldn't download https://github.com/davidswelt/aquamacs-emacs/releases/download/Aquamacs-3.2/Aquamacs-Emacs-3.2.dmg: HTTP Error 404: Not Found
It seems like the version numbers have drastically changed for this location.

Would it be possible to revamp this to download from here?
http://aquamacs.org/download-release.shtml

Thanks,

Jake

**Comment by hansen-m** [comment]
Sure, I'll take a look. Thanks for reporting it.

**Comment by jakerundall** [comment]
No problem.  Thanks!  Let me know if I can help test anything.

Jake

**Comment by hansen-m** [comment]
That was easy. Pushed an updated version.

**Comment by jakerundall** [comment]
Thanks!
