### ISSUE TITLE
GoogleChrome-Win recipe error BESRelevanceProvider

### ISSUE THREAD

**Issue by patgmac** [autopkg/hansen-m-recipes#28]
When I run the GoogleChrome-Win.download recipe, I get a "unknown processor BESRelevanceProvider'. 

Known issue?

**Comment by hansen-m** [comment]
```autopkg install BESEngine```

If you look at the BESRelevanceProvider you'll see that it also depends on the QnA utility from IBM. I've been meaning to create an install recipe for QnA, I'll try to get to that soon.

**Comment by hansen-m** [comment]
Another thing I've been debating is even doing this kind of version checking inside the download recipe or leave that up to the child recipes. With what you are trying to use it for do you need the version string or would your recipes or software distribution handle that?

**Comment by patgmac** [comment]
I would prefer version string added to file name given the choice. %name%-%version%.extension. Makes it easier to confirm which version was downloaded instead of assuming it was the same as a Mac counterpart. Also, Macs have no way of determining version of an Windows file.

**Comment by patgmac** [comment]
I got the BESEngine installed, but now get the following error: 

```
autopkg run GoogleChrome-Win.download
Processing GoogleChrome-Win.download...
[Errno 2] No such file or directory
Failed.

The following recipes failed:
    GoogleChrome-Win.download
        Error in com.github.hansen-m.download.googlechrome-Win: Processor: com.github.hansen-m.SharedProcessors/WinInstallerExtractor: Error: [Errno 2] No such file or directory

Nothing downloaded, packaged or imported.
```

Is the filename extension missing from the processor?

**Comment by hansen-m** [comment]
There are a few ways of determining versions of files, it requires some digging and a few extra steps but I've had a fair amount of luck with it.

The WinInstallerExtractor processor uses 7z, so you just need to install it on your system (Homebrew, MacPorts or manually) and have it somewhere in your PATH.

**Comment by hansen-m** [comment]
Added some new recipes here - https://github.com/autopkg/hansen-m-recipes/tree/master/IBM

Try `autopkg install QnA`

**Comment by hansen-m** [comment]
Did this end up working out for you?

**Comment by patgmac** [comment]
Sorry, this slipped off my radar. I am able to run GoogleChrome-Win.download now, I have QnA installed, I have /usr/local/bin/7z installed. Should I be getting version numbers as part of the output filename? Or is that not implemented yet?

**Comment by hansen-m** [comment]
It doesn't rename the change the output filename, is that something that would be required for your software distribution system? You could also use the copier or file mover processors in your child recipe using the %pathname% and %version% variables.

**Comment by patgmac** [comment]
I wouldn't say it (LANrev/AM) "requires" it, but otherwise you have no way of knowing what version was downloaded. I don't see the %version% in the receipt. Is that retrieved as part of the recipe?

**Comment by hansen-m** [comment]
Yes, the %version% variable will be available in your child recipes. It doesn't appear in the receipt since it isn't a declared output variable because it is dynamically named by the output_var_name key to the processor.
