### ISSUE TITLE
add etag data to bigfix metadata in generated .bes file

### ISSUE THREAD

**Issue by jgstew** [autopkg/hansen-m-recipes#29]
It would be interesting to add etag data to the generated BigFix task in the metadata, perhaps in a MIME field, and/or an action script comment. This could be used by autopkg or other automation of BigFix content for de-duplication and other purposes. 

I could see this as useful metadata for all results of autopkg recipes to carry through. 

This would allow the thing doing the automation to be more stateless other than the generated results that are already in the distribution platform anyway.

**Comment by hansen-m** [comment]
Fully agreed although de-duplication would require more complex API calls compared to the current method of comparing the task names.

**Comment by jgstew** [comment]
This is true, that it would require more complicated API calls, but adding the etag data is a step towards that in the future. I see this as something that would be useful to add at some point, definitely not anything critical.

**Comment by rustymyers** [comment]
AutoPkgBESEngine has this built in using bes_additionalmimefields. It seems to work well!

        
        <key>bes_additionalmimefields</key>
        <dict>
          <key>x-app-vendor</key>
          <string>EXAMPLE Vendor</string>
          <key>x-app-title</key>
          <string>%NAME%</string>
          <key>x-app-version</key>
          <string>%version%</string>
          <key>x-app-platform</key>
          <string>Windows</string>
