### ISSUE TITLE
github.hansen-m.SharedProcessors/WinInstallerExtractor

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/hansen-m-recipes#38]
I am having an error that Pat G was having.  He suggested to contact you.  I have the engine installed and I am getting the MSI but I am failing on 7zip.  I do have 7zip installed.  Not sure what I am missing. 

The following recipes failed:
    /Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.patgmac-recipes/Google Chrome/GoogleChrome-Win64.LANrev.recipe
        Error in com.github.patgmac.lanrev.GoogleChrome-Win64: Processor: com.github.hansen-m.SharedProcessors/WinInstallerExtractor: Error: Command '['7z', 'x', '-y', u'-o/Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/InstallerExtract', u'/Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/downloads/GoogleChrome x64.msi']' returned non-zero exit status 2

Let me know if anything comes to mind.  I know 7zip but I just don't know what.

Thanks
-Jeff

**Comment by hansen-m** [comment]
It seems that exit 2 is just listed as "fatal error".

Can you try running...
```which 7z```

```ls -alh /Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/downloads/GoogleChrome\ x64.mi```

And finally...
```7z x -y /Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/downloads/GoogleChrome\ x64.mi```

**Comment by jfuchtm** [comment]
Appears that is not crashing, but not able to process the file?

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)
Can't load './7z.dll' ()


Error:
7-Zip cannot find the code that works with archives.

**Comment by jfuchtm** [comment]
ausst:~ ladmin$ which 7z
/usr/local/bin/7z

ausst:~ ladmin$ ls -alh /Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/downloads/GoogleChrome\ x64.mi
ls: /Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/downloads/GoogleChrome x64.mi: No such file or directory

ausst:~ ladmin$ 7z x -y /Users/ladmin/Library/AutoPkg/Cache/com.github.patgmac.lanrev.GoogleChrome-Win64/downloads/GoogleChrome\ x64.mi

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)
Can't load './7z.dll' ()


Error:
7-Zip cannot find the code that works with archives.

**Comment by jgstew** [comment]
Could be due to this: "[Generally 7zip related errors are due to space in the link.](https://sourceforge.net/p/multibootusb/bugs/3/)"

I wonder if 7zip is having issues with the `\ ` before the `x64.msi`

It could also be that "[7z.dll is missing](https://sourceforge.net/p/sevenzip/discussion/45797/thread/a01e0ce7/)"

### References:
- https://sourceforge.net/p/multibootusb/bugs/3/

**Comment by hansen-m** [comment]
Yep, you could try removing the space but if that fixes it then that would seem to be a bug in the code. I just tested it manually with a space in the name and it worked fine.

How did you install 7z?

**Comment by jgstew** [comment]
I do wonder if this would work with MSIs if it supports CAB files, which it appears to: https://pypi.python.org/pypi/libarchive

**Comment by hansen-m** [comment]
This seems to be just a 7z installation issue.

I was able to reproduce this by using an older version of of 7z (9.2) and separating the binary from the 7z.so file into different directories, (I take it the error dialog is just poorly worded by referencing the .dll). I'd suggest grabbing a more recent copy of 7z by installing it (p7zip) from either MacPorts or Homebrew. Or a lot of the GUI archive extractors (TheUnarchiver, Keka) just include the 7z binaries inside the app bundle that you could symlink to.

**Comment by jfuchtm** [comment]
That cured the issue.  Thanks for the help!!!
