### ISSUE TITLE
Update recipes to use BESRelevanceProvider SharedProcessor path

### ISSUE THREAD

**Issue by blimvisible** [autopkg/hansen-m-recipes#44]
One example: running GoogleChrome-Win.download recipe fails with error "Unknown processor 'BESRelevanceProvider'." I believe this is because it references the processor as  'BESRelevanceProvider' and not by the full SharedProcessor path 'com.github.hansen-m.SharedProcessors/BESRelevanceProvider' instead.

Apologies if the culture surrounding this sort of thing should be "fix it yourself and make a pull request" but I just started with git and don't know how to do any of that.

**Comment by hansen-m** [comment]
Must have missed that one, thanks for letting me know. Fixed now.

**Comment by blimvisible** [comment]
I created a pull request with some others -- first time, hopefully I did it correctly.

**Comment by jgstew** [comment]
You did make the pull request correctly.
