### ISSUE TITLE
Shift Key Doesn't work with Ibus-Pinyin

### ISSUE THREAD

**Issue by ping-wu** [autopkg/hansen-m-recipes#58]
Running UbuntuMate 16.04.  When using Ibus-Pinyin to input Chinese and English characters in texmaker , shift-key (_L or _R）doesn't shift the input mode. It works in all other applications. I can still use Ctrl-space (or Super-space) to toggle between English and Chinese keyboards.  Same problem was reported in other versions of (at least) Ubuntu.

**Comment by gregneagle** [comment]
@ping-wu: this repo contains "recipes" for use with autopkg (https://github.com/autopkg/autopkg), a systems administration tool that is primarily targeted for Mac OS X.

I'm not sure what project you were trying to report an issue against, but I'm pretty sure it's not this one.
