### ISSUE TITLE
Inkscape recipe downloads old version

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/hansen-m-recipes#6]
Hi
Inkscape.download.recipe downloads Inkscape version **0.48.5** from **28 July 2014**
Current available is **0.91** from **February 2015**

**Comment by hansen-m** [comment]
It looks like the current stable version is still 0.48.5 - http://sourceforge.net/projects/inkscape/files/inkscape/

**Comment by hansen-m** [comment]
It might be worth adding an option to specify in an override if you want the latest stable or a pre-release version. Are there new features in the latest version that make it worthwhile? Are the pre-release versions stable enough for general deployment?

**Comment by MichalMMac** [comment]
Acording to their web page latest stable is 0.91 https://inkscape.org/en/download/mac-os/

**Comment by hansen-m** [comment]
Very confusing, they don't even have that version posted on their SourceForge page.

**Comment by hjuutilainen** [comment]
The only reference to SourceForge on their site is in the website upgrade announcement:
https://inkscape.org/en/news/2014/09/04/inkscape-website-upgrade/

"This upgrade should also allow release file and Addons/extentions to be hosted directly on the site instead of on sourceforge and other file searching services. Improving inkscape's delivery of pre-built binaries to users."

Are they abandoning SourceForge?

**Comment by hansen-m** [comment]
Updated the Inkscape recipe to scrape the link from their download page.

**Comment by MichalMMac** [comment]
Error in com.github.hansen-m.download.Inkscape: Processor: URLDownloader: Error: Couldn't download https://inkscape.org/en/gallery/item/3896/Inkscape-0.91-1-x11-10.7-x86_64.dmg: HTTP Error 404: OK

**Comment by hansen-m** [comment]
Looks like the download link is a 404 at the moment...

https://inkscape.org/en/download/mac-os/

**Comment by rustymyers** [comment]
Appears to be downloading now, but the latest version is no longer available on the page. It would seem this project requires it be installed through MacPorts.

**Comment by rustymyers** [comment]
Version 0.91 is currently being grabbed with this recipe. Later versions are not distributed with a dmg and should be installed through other methods unless anyone wants to create a recipe to install the latest through open source tools and pkg for distribution.
