### ISSUE TITLE
SubEthaEdit 3 download recipe

### ISSUE THREAD

**Issue by homebysix** [autopkg/hansen-m-recipes#63]
Your SubEthaEdit recipe links to a download URL with a hard-coded version. I can see two potential issues with this:
- If version 3.5.5 is ever released, your URL won't grab it.
- Major version 4 is now available, and it's only in the App Store.

It might be time to retire the SubEthaEdit recipe, given the above.

**Comment by rustymyers** [comment]
Latest commit resolves this issue with SubEthaEdit!
