### ISSUE TITLE
Unity3DComponetsURLProvider.py doesn't find the Version

### ISSUE THREAD

**Issue by paulbloch** [autopkg/hansen-m-recipes#67]
It looks like they changed the format on the "whats-new" page.

sysadmin@beta: ~ 38$ autopkg run Unity3D.munki
Processing Unity3D.munki...
Unable to find latest version string in http://unity3d.com/unity/whats-new.
Failed.

The following recipes failed:
    Unity3D.munki
        Error in local.munki.Unity3D: Processor: Unity3DComponetsURLProvider: Error: Unable to find latest version string in http://unity3d.com/unity/whats-new.

Nothing downloaded, packaged or imported.

**Comment by hansen-m** [comment]
Should be fixed now, give it a try and let me know if it doesn't work. Thanks!

**Comment by timsutton** [comment]
```python
  File "/Users/tsutton/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Unity3D/Unity3DComponetsURLProvider.py", line 47, in Unity3DComponetsURLProvider
    "Defaults to %s" % (SEARCH_URL),
NameError: name 'SEARCH_URL' is not defined
```

Looks like it's missing a constant `SEARCH_URL` within Unity3DComponetsURLProvider.py. Thanks for doing this recipe!

**Comment by hansen-m** [comment]
@timsutton Doh! Thanks, fixed it.
