### ISSUE TITLE
No match found on URL : Mega Software Download Recipe Fails 

### ISSUE THREAD

**Issue by tcinbis** [autopkg/hansen-m-recipes#68]
Seems like they changed something on the website.
```
autopkg run -v com.github.hansen-m.download.mega
Processing com.github.hansen-m.download.mega...
URLTextSearcher
No match found on URL: http://www.megasoftware.net/releases/?C=M;O=D
Failed.
Receipt written to /Users/userxy/Library/AutoPkg/Cache/com.github.hansen-m.download.mega/receipts/com.github.hansen-m.download-receipt-20161121-122329.plist

The following recipes failed:
    com.github.hansen-m.download.mega
        Error in com.github.hansen-m.download.mega: Processor: URLTextSearcher: Error: No match found on URL: http://www.megasoftware.net/releases/?C=M;O=D

Nothing downloaded, packaged or imported.
```

**Comment by jgstew** [comment]
The recipe: https://github.com/autopkg/hansen-m-recipes/blob/54f0ea9cce2bf0546b1b191901671c976d8d9fb0/MegaSoftware/Mega.download.recipe

The URL definitely doesn't seem to work anymore: http://www.megasoftware.net/releases/?C=M;O=D

The URL does seem to return HTML, just completely empty

When you go to download it from the website, it seems to go to a download form now: http://www.megasoftware.net/download_form

**Comment by jgstew** [comment]
I actually sent the vendor a tweet about this: https://twitter.com/jgstew/status/800776266550898688

**Comment by tcinbis** [comment]
I used their feedback site on der website. 
Maybe they will change something.

**Comment by jgstew** [comment]
I also just submitted a user feedback on their site:

![software_version_mega](https://cloud.githubusercontent.com/assets/2439367/20496647/e65ec60e-afda-11e6-9981-f5738135ac0e.PNG)

**Comment by jgstew** [comment]
This should be the RegEx to pull the version numbers from: http://www.megasoftware.net/history

`\) MEGA(\d+.\d+.\d+) build \d+`

**Comment by hansen-m** [comment]
@jgstew Unfortunately the history page doesn't seem to be entirely up to date. The latest version is MEGA7.0.21 but /history lists MEGA7.0.14 build 7160126.

**Comment by jgstew** [comment]
@hansen-m I agree that the history page is problematic, which is why I submitted to the company to keep it up to date. As of now the history page is the best I could find as an option to get latest version to try to figure out a download URL from.  I don't know if there is a better option that is direct from the vendor for this software.

**Comment by hansen-m** [comment]
This is about as close as I could get but it would take some time to re-work this into a custom URL provider:

```
curl -H "Cookie: PHPSESSID=28u6a5anh8tiiupejm4kg5e2u6" -H "Referer: http://www.megasoftware.net/dload_mac_gui" --data "ci_csrf_token=&country=United+States&user_type%5B%5D=4&user_custom_type=IT&institution=Penn+State+University&institution_type%5B%5D=0&institution_custom_type=&email=" http://www.megasoftware.net/active_download
```

The 'Referer' header doesn't seem to be necessary but I can't seem to figure out how to pick which download is provided. It seems to switch indiscriminately based on the last download page you loaded in a browser, which might be tied to the `PHPSESSID`.

**Comment by hansen-m** [comment]
As a workaround I've just hardcoded the direct disk image url into the recipe which oddly enough seems to work (given how much work the vendor put into the registration form and obfuscating the url).

**Comment by tcinbis** [comment]
@hansen-m Thanks!

**Comment by jfuchtm** [comment]
I have been trying to work your Windows recipes on a new Mac install of AutoPkg and I am running into a stone wall.  I have wine and 7zip installed via MacPorts but I am still seeing the following errors.  Any assistance would be appreciated.

 

AutoPkgr:~ ladmin$ autopkg run /Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Google/GoogleChrome-Win64.download.recipe 

Traceback (most recent call last):

  File "/usr/local/bin/autopkg", line 36, in <module>

    import autopkglib.github

  File "/Library/AutoPkg/autopkglib/__init__.py", line 627, in <module>

    import_processors()

  File "/Library/AutoPkg/autopkglib/__init__.py", line 530, in import_processors

    mydirname + '.' + name, fromlist=[name]), name)

  File "/Library/AutoPkg/autopkglib/AutoPkgBESEngine.py", line 23, in <module>

    import requests

 

 

 

Jeff Uchtman 

District Network & Systems Administrator

Columbus Public Schools

2508 27th Street

Columbus, NE 68601

402-563-7000 ext. 12352

uchtmanj@discoverers.org

 

In God we trust, all others we virus scan.  ~Author Unknown

**Comment by jgstew** [comment]
@jfuchtm can you please open a new issue for this? https://github.com/autopkg/hansen-m-recipes/issues/new

**Comment by jfuchtm** [comment]
Submitted, thanks
