### ISSUE TITLE
Attempting to run Windows recipies with error

### ISSUE THREAD

**Issue by jfuchtm** [autopkg/hansen-m-recipes#70]
I have been trying to work your Windows recipes on a new Mac install of AutoPkg and I am running into a stone wall.  I have wine and 7zip installed via MacPorts but I am still seeing the following errors.  Any assistance would be appreciated.
 
AutoPkgr:~ ladmin$ autopkg run /Users/ladmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.hansen-m-recipes/Google/GoogleChrome-Win64.download.recipe 
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 36, in <module>
    import autopkglib.github
  File "/Library/AutoPkg/autopkglib/__init__.py", line 627, in <module>
    import_processors()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 530, in import_processors
    mydirname + '.' + name, fromlist=[name]), name)
  File "/Library/AutoPkg/autopkglib/AutoPkgBESEngine.py", line 23, in <module>
    import requests

**Comment by jgstew** [comment]
At the very bottom, I see `import requests`.

Do you have requests installed? I don't think that is included with the python standard library, so I think that is the issue.

If you tried to run a .py file that only contained the line `import requests` do you get an error?

**Comment by jfuchtm** [comment]
I am not sure what happened.  I do use LANrev importer.  What I finally did to correct was to completely remove AutoPkr and AutoPkgr and reinstall.  All is working from both CLI and GUI.  I think it was something to do with the importer.

**Comment by jgstew** [comment]
That is a bit odd that removing and re-adding autopkgr would have resolved it. Was it a newer version of AutoPkgr?

**Comment by jfuchtm** [comment]
1.4.2
