### ISSUE TITLE
Error running R Studio recipe

### ISSUE THREAD

**Issue by mmcphail** [autopkg/hansen-m-recipes#73]
I am getting the following error:

The following recipes failed:
    RStudio.munki
        Error in local.munki.RStudio: Processor: URLDownloader: Error: Curl failure: Could not resolve host: %DOWNLOAD_MIRROR% (exit code 6)

I am calling this through the recipe in joshua-d-millers RStudio.munki.recipe.  Am I missing something?

**Comment by jgstew** [comment]
I'm not certain, but it seems like `%DOWNLOAD_MIRROR%` isn't being replaced by the real value properly. 

This seems to be what you are running: https://github.com/autopkg/joshua-d-miller-recipes/blob/master/RStudio/RStudio.munki.recipe

This seems to be the download recipe with the issue: https://github.com/autopkg/hansen-m-recipes/blob/master/RStudio/RStudio.download.recipe

It looks like `%DOWNLOAD_MIRROR%` should be set to `https://download1.rstudio.org`

**Comment by jgstew** [comment]
Looking over the proper download link, the regex, and what the recipe is doing, it all looks correct at a glance.

**Comment by mmcphail** [comment]
Line 41(<string>%DOWNLOAD_MIRROR%/%dmg%</string>) doesn't seem right to me.  I don't see any assignment for %dmg%.

**Comment by jgstew** [comment]
dmg should be assigned here:

```
<key>SEARCH_PATTERN</key>
<string>(?P&lt;dmg&gt;
```
