### ISSUE TITLE
MeshLab recipe does not download latest version

### ISSUE THREAD

**Issue by jazzace** [autopkg/hansen-m-recipes#83]
The latest version of MeshLab (2016.12) is not being downloaded by the recipe. It looks like they have moved from SourceForge to GitHub. Basically, the recipe needs to be rewritten from scratch. I can do that work it and post to my own repo (since I'll also be writing a pkg recipe as well) or I can put in a pull request. Take your pick.

**Comment by rustymyers** [comment]
Hey Anthony, I updated the MeshLab recipes to pull from the GitHub releases.
