### ISSUE TITLE
Texmaker 5

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/hansen-m-recipes#87]
Texmaker appears to have new version with new link.
Current download link points to http://www.xm1math.net/texmaker/assets/files/texmaker-5.0.2.dmg

Texmakerd.download AutoPkg recipe downloads version 4.5 at http://www.xm1math.net/texmaker/TexmakerMacosxLion.zip

**Comment by rustymyers** [comment]
Updated recipes in latest commit to fetch the latest version of Texmaker.
