### ISSUE TITLE
iTunes-Win.download old version

### ISSUE THREAD

**Issue by rustymyers** [autopkg/hansen-m-recipes#92]
iTunes-Win.download isn't finding the latest version. It seems the URL the recipe uses isn't being updated anymore.  https://www.apple.com/itunes/download/ seems to include the correct URL to download the exe, but autopkg can't find the URL when it curls it. I can find the url in the curl, but can't find any reason the regex isn't working.

**Comment by jgstew** [comment]
So this issue is here: https://github.com/autopkg/hansen-m-recipes/blob/master/Apple/iTunes-Win.download.recipe#L16 ?

**Comment by rustymyers** [comment]
This doesn't seem to be an issue any longer. Not sure if something was "fixed" or what, but I can't recall now.
