### ISSUE TITLE
Adobe Digital Editions pkg not signed any more

### ISSUE THREAD

**Issue by fuzzylogiq** [autopkg/hansen-m-recipes#93]
```
$ pkgutil --check-signature /Volumes/ADE\ 4.5/Digital\ Editions\ 4.5\ Installer.pkg
Package "Digital Editions 4.5 Installer.pkg":
   Status: no signature
```

Possibly an oversight? I've tweeted @Adobe but no idea if that will have any effect. If anyone has a better support route, please can they try and let them know?

**Comment by foigus** [comment]
I tweeted to **@adobecare** about this issue [here](https://twitter.com/foigus/status/979002488182460417).

They asked for a forum post, that's [here](https://forums.adobe.com/message/10276485).

**Comment by foigus** [comment]
[Adobe response](https://forums.adobe.com/message/10287841#10287841):

> AJIT_M Employee Apr 3, 2018 4:03 AM (in response to Patrick Fergus)
>  
> Hi There,
>  
> This is a known issue with Adobe Digital Edition v4.5.7 on Mac OS. We are working on it on priority and once we have a fix available then I will definitely update you.
>  
> Regards,
> Ajit

**Comment by foigus** [comment]
Appears Adobe Digital Editions 4.5.8 was released in the last 24 hours and is properly signed.  This issue can be closed.
